import {
  Controller,
  Get,
  Post,
  Body,
  UseGuards,
} from '@nestjs/common';
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiBearerAuth,
} from '@nestjs/swagger';
import { DiscountsService } from './discounts.service';
import { GenerateDiscountDto } from './dto/generate-discount.dto';
import { JwtAuthGuard, RolesGuard } from '../auth/guards';
import { CurrentUser, IsSeller, IsAdmin } from '../common';

@ApiTags('Discounts')
@Controller('discounts')
export class DiscountsController {
  constructor(private readonly discountsService: DiscountsService) {}

  @Get()
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth('JWT-auth')
  @ApiOperation({ summary: 'Get my available discount codes' })
  @ApiResponse({
    status: 200,
    description: 'Discount codes retrieved successfully',
  })
  getMyDiscountCodes(@CurrentUser('userId') userId: string) {
    const codes = this.discountsService.getCustomerDiscountCodes(userId);
    return {
      success: true,
      codes,
    };
  }

  @Get('seller/discounts')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @IsSeller()
  @ApiBearerAuth('JWT-auth')
  @ApiOperation({ summary: 'Get discount codes generated by seller' })
  @ApiResponse({
    status: 200,
    description: 'Discount codes retrieved successfully',
  })
  getSellerDiscountCodes(@CurrentUser('userId') sellerId: string) {
    const codes = this.discountsService.getSellerDiscountCodes(sellerId);
    return {
      success: true,
      codes,
    };
  }

  @Post('seller/discounts/generate')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @IsSeller()
  @ApiBearerAuth('JWT-auth')
  @ApiOperation({ summary: 'Generate a discount code manually' })
  @ApiResponse({
    status: 201,
    description: 'Discount code generated successfully',
  })
  generateDiscountCode(
    @CurrentUser('userId') sellerId: string,
    @Body() generateDto: GenerateDiscountDto,
  ) {
    const code = this.discountsService.generateDiscountCode(
      sellerId,
      generateDto.discountPercentage,
      generateDto.customerId,
      generateDto.expiresAt,
    );
    return {
      success: true,
      message: 'Discount code generated successfully',
      code,
    };
  }

  @Get('admin/discounts')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @IsAdmin()
  @ApiBearerAuth('JWT-auth')
  @ApiOperation({ summary: 'Get all discount codes (Admin)' })
  @ApiResponse({
    status: 200,
    description: 'All discount codes retrieved successfully',
  })
  getAllDiscountCodes() {
    const codes = this.discountsService.getAllDiscountCodes();
    return {
      success: true,
      codes,
    };
  }
}
